#:schema node_modules/wrangler/config-schema.json
name = "twikoo-cloudflare"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "twikoo-db"
database_id = "a0800afa-9c3a-4724-a1ba-f07b660ef66a"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo-db"

[vars]
R2_PUBLIC_URL = "https://twikoo-r2.pre-trainedhuman.com"

[dev]
port = 5000
